name         'nvogel-ansible'
version      '2.0.0'
license      'MIT'
summary      'Ansible'
description  'Orchestration of Puppet nodes with Ansible'
project_page 'https://github.com/nvogel/puppet-ansible'
dependency   'puppetlabs/stdlib', '>= 4.2.2'
