name         'nvogel-ansible'
version      '1.1.0'
license      'MIT'
summary      'Ansible'
description  'Install Ansible on a master host and allow ssh connections from it to a pool of managed hosts'
project_page 'https://github.com/nvogel/puppet-ansible'
dependency   'puppetlabs/stdlib'
